services:
  backend:
    image: brittanynoe/workshop_registration_system:latest
    container_name: spring-api-container
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mysql:latest
    container_name: mysql_database
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: workshopdb
      MYSQL_USER: user
      MYSQL_PASSWORD: secret_pass_user
    ports:
      - 3307:3306
    networks:
      - spring-network
    volumes:
      - mysql-volume:/var/lib/mysql
networks:
  spring-network:
volumes:
  mysql-volume:
  