services:
  backend:
    image: brittanynoe/workshop_registration_system:latest
    container_name: spring-api-container
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:17
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - 5432:5432
    networks:
      - spring-network
    volumes:
      - db_data:/var/lib/postgresql/data
networks:
  spring-network:
volumes:
  db_data:
  